# Generated by Django 4.2.6 on 2023-11-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('imagem1', models.ImageField(blank=True, upload_to='')),
                ('imagem2', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
